module.exports = {
    aahk: require("./aahk"),
    hko: require("./hko"),
    ogcio: require("./ogcio"),
    devb: require("./devb"),
    lcsd: require("./lcsd"),
    hse: require("./hse"),
    effo: require("./effo"),
    geo: require("./geodata"),
    dh: require("./dh"),
    ha: require("./ha"),
    hkma: require("./hkma"),
    dc: require("./dc"),
    hkpf: require("./hkpf"),
    legco: require("./legco"),
}