module.exports = {
    Address: require("./Address"),
    Airport: require("./Airport"),
    Airline: require("./Airline"),
    Building: require("./Building"),
    Carpark: require("./Carpark"),
    Coordinate: require("./Coordinate"),
    CoordinateValue: require("./CoordinateValue"),
    District: require("./District"),
    Direction: require("./Direction"),
    Estate: require("./Estate"),
    Flat: require("./Flat"),
    Flight: require("./Flight"),
    HKOStation: require("./HKOStation"),
    Lamppost: require("./Lamppost"),
    Location: require("./Location"),
    Region: require("./Region"),
    UnitValue: require("./UnitValue"),
}